spring:
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  thymeleaf:
    cache: false
  datasource:
    druid:
      initial-size: 5
      max-active: 10
      max-wait: 3000
server:
  port: 8188
  servlet:
    context-path: /sql


#mybatis:
#  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
# 日志
#logging:
#  config: classpath:log4j2.yml


